
name: cicd pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
 
jobs:
  compile:
    runs-on: Agent-1
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: set up java 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: build with maven
        run: mvn compile 

  Trivy-security-scan:
    runs-on: Agent-1
    needs: compile
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-output.json'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  Gtleaks-Scan:
    runs-on: Agent-1
    needs: Trivy-security-scan
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Gitleaks Installation
        run: sudo apt install gitleaks -y

      - name: GitLeaks code Scan
        run: gitleaks detect source . -r gitleaks-report.json -f json

      
      
      
        

 
        
        
      


  

  
