
name: java-project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: "0 5 * * *"

jobs:
  compile:
    runs-on: Agent-1

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: compile
        run: mvn compile
      
    
  
      
        

 
        
        
      


  

  
