name: cicd pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  compile:
    runs-on: Agent-1

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: set up java 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: build with maven
        run: mvn compile
        
          


  

  
